openapi: 3.0.1
info:
  title: cards-session-mobile-sdk
  description: 
  x-cortex-git:
    github:
      repository: xendit/cards-session-mobile-sdk
  x-cortex-tag: cards-session-mobile-sdk
  x-cortex-dependency: []
  x-cortex-service-groups:
    - P2
    - shaun@xendit.co
  x-cortex-owners:
    - type: EMAIL
      email: shaun@xendit.co
    - type: GROUP
      name: xendit/charge
    - type: GROUP
      name: xendit/cards-production
    